### ISSUE TITLE
порівняння з булевським значенням

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-12-JS-conditions-loops#1]
https://github.com/BohdanLuts/home-work-lesson-12-JS-conditions-loops/blob/0ff5fc1da216a3b63508aef969443e09a0126317/js/index.js#L14
- загальноприйнятим є запис:
`if (test)`
оскільки в test і так зберігається булевське значення.

https://github.com/BohdanLuts/home-work-lesson-12-JS-conditions-loops/blob/0ff5fc1da216a3b63508aef969443e09a0126317/js/index.js#L20
- аналогічно,
`if (!test)`

**Comment by BohdanLuts** [comment]
Беру до уваги.
