### ISSUE TITLE
порівняння 

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-12-JS-conditions-loops#2]
https://github.com/BohdanLuts/home-work-lesson-12-JS-conditions-loops/blob/0ff5fc1da216a3b63508aef969443e09a0126317/js/index.js#L30
- зверніть увагу на формулювання в умові при порівнянні: "якщо більше 500" чи "якщо більше або дорівнює 500". Аналогічно і для 800.

**Comment by BohdanLuts** [comment]
Переробив як у завданні.

Зробив 500 включно більше с життя ніж з ТЗ, а от по 800 включно - вийшло, що для 799 - знижка 3%, для 801 = 5%. а для 800 - не в межах діапазону (значення, як для менше та дорівнює 500).

**Comment by pecourses** [comment]
З ТЗ виходе, що для 800 має бути 3%, тобто 3% починається з 500 (не включно) та до 800 (включно).

**Comment by pecourses** [comment]
На даний момент при 800 знижки нема. Покупець буде здивований)

**Comment by BohdanLuts** [comment]
Виправив для 800.
